language: android
jdk: openjdk7
android:
  components:
    - build-tools-25.0.3
    # The SDK version used to compile your project
    - android-25
    - extra-android-m2repository
    - extra-android-support
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
script:
  - ./gradlew build
  - ./gradlew packageDebugAndroidTest
before_deploy:
  - mv app/build/outputs/apk/app-release.apk app/build/outputs/apk/app-uiautomator.apk
  - mv app/build/outputs/apk/app-debug-androidTest.apk app/build/outputs/apk/app-uiautomator-test.apk